### ISSUE TITLE
400 Invalid Request Headers / Couldn't ping the API

### ISSUE THREAD

**Issue by brad-newman** [solid-pixel/vscode-cloudflareDevTools#4]
Triple checked all keys, IDs, permissions. Restarted VS Code. Let me know how I can access more information to help debug.

**Comment by solid-pixel** [comment]
What does `Output → Cloudflare DevTools | Logs` show?

I'm not using the extension anymore but I've just tested it and it still works fine with this config:

<img width="646" alt="image" src="https://github.com/solid-pixel/vscode-cloudflareDevTools/assets/18260178/91728b4a-e743-4375-b552-95b277a726fe">

**Comment by wildernessfamily** [comment]
I'm having the same problem.
Initially I received:
```text
Could not route to
Could not route to /client/v4/zones/settings/development_mode, perhaps your object identifier is invalid? (404)
Source: CloudFlare Dev Tools (Extension)
```
Each time I try to ping the CloudFlare server or perform any type of call (Dev on/off) I receive:
```text
Invalid request headers (400)
Source: CloudFlare Dev Tools (Extension)
```
Output → CloudFlare DevTools | Logs
```text
[11:42:29] [Development Mode] Error: Invalid request headers (400)
[11:43:19] [Development Mode] Error: Could not route to /client/v4/zones/settings/development_mode, perhaps your object identifier is invalid? (404)
[11:44:27] [Development Mode] Error: Invalid request headers (400)
[11:46:19] [Development Mode] Error: Invalid request headers (400)
[11:46:44] [Development Mode] Error: Could not route to /client/v4/zones/settings/development_mode, perhaps your object identifier is invalid? (404)
[11:49:10] [Development Mode] Error: Invalid request headers (400)
```

I have verified the API, email address, and Zone ID are correct.
FYI, I spoke to CloudFlare and I worked my way though different tech supports and one stated they are changing their API call names. I had been working on another app that used CloudFlare API.

**My Specs**

**Hardware**
MacBook Pro | macOS Monterey 12.7.1

**Extension:** Cloudflare DevTools v1.0.3

**VSCode**
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0

**Comment by solid-pixel** [comment]
I'm so sorry guys, I just realized the API Token you need to use is actually the `Global API Key`. The README was wrongly referencing to another kind of token, I've now updated it with the correct instructions.

In short, please set `cloudflareDevTools.api.key` to your **Global API Key**, which can be found [here](https://dash.cloudflare.com/profile/api-tokens) at the bottom of the page. 

@wildernessfamily thank you so much for the detailed report, I really appreciate that!

**Comment by wildernessfamily** [comment]
Easy change. Thanks for the info.
